---
apiVersion: v1
kind: Service
metadata:
  name: launcher-service
spec:
  ports:
  - name: launcher-service-http
    nodePort: 31782
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moop
    service: launcher-service
  type: NodePort
