---
apiVersion: v1
kind: ConfigMap
metadata:
  name: launcher-worker-config

data:
  config.yaml: |-
    host: '0.0.0.0'
    port: 5000
    debug: true
    log_level: 10
    status_check_interval: 1
    status_check_count: 120
    jupyterhub_service_prefix: '/services/launcher/'
    jupyterhub_url: 'http://hub:8081'
    jupyterhub_api_prefix: '/hub/api'
    jupyterhub_api_token: 'ad6b8dc16f624b54a5b7d265f0744c98'
    user_token_lifetime: 86400
    namespace: 'moop-ce'
  celery_config.py: |-
    broker_url = 'redis://:d2VsY29tZTEK@rd-redis-ha-haproxy.redis.svc:6379/0'
    result_backend = 'redis://:d2VsY29tZTEK@rd-redis-ha-haproxy.redis.svc:6379/0'
    enable_utc = True
